<div id="custom-component" data-bind="scope:'customcomponent'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "#custom-component": {
        "Magento_Ui/js/core/app": {
           "components": {
                "customcomponent": {
                    "component": "Adobe_KnockoutExercise/js/custom-component"
                }
            }
        }
    }
}
</script>